api_url : https://mibhwzdakf.execute-api.eu-west-1.amazonaws.com/api/
credentials:
  username: 'master-fibeg'
  password: 'Os_test123'
domain:
  endpoint: https://search-sematic-search-4vgtrb5lpgqsss26pxewnosnjy.eu-west-1.es.amazonaws.com
  index: rfp-nestle
  index_legal: legal-passages
  index_aws_sc: aws-supply-chain
  index_products: products-metadata
  index_manual_xc402020: manual-xc40-2020
bedrock-preview:
  endpoint: 'https://prod.us-west-2.frontend.bedrock.aws.dev'
  region: 'us-west-2'