name: CDK Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Install NPM
          run: |
            sudo apt-get update -y
            sudo apt-get install nodejs npm -y

        - name: Install AWS CDK
          run: sudo npm install -g aws-cdk

        - name: Install Python dependencies
          run: python -m pip install -r requirements.txt
          working-directory: streamlit/Infrastructure
        
        - name: CDK Synth
          run: cdk synth
          working-directory: streamlit/Infrastructure
          env:
            CDK_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
            CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        
        - name: CDK Deploy
          run: cdk deploy --require-approval never
          working-directory: streamlit/Infrastructure
          env:
            CDK_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
            CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
